Parameters:

  BucketName:
    Type: String

  CdseUsername:
    Type: String
    NoEcho: true

  CdsePassword:
    Type: String
    NoEcho: true

Resources:

  Bucket:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        DataSetName: !Ref BucketName
      TemplateURL: apps/bucket/cloudformation.yml

  Api:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        BucketName: !GetAtt Bucket.Outputs.DataBucket
      TemplateURL: apps/api/cloudformation.yml

  Fetcher:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        BucketName: !GetAtt Bucket.Outputs.DataBucket
        CdseUsername: !Ref CdseUsername
        CdsePassword: !Ref CdsePassword
      TemplateURL: apps/fetcher/cloudformation.yml
