name: sentinel1-orbits
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - pip
  - pytest
  - ruff
  - responses
  - pip:
      - -r requirements-api.txt
      - -r requirements-fetcher.txt
