name: Deploy to AWS
description: Deploys a copy of the application to AWS via CloudFormation

inputs:
  AWS_ACCESS_KEY_ID:
    required: true
  AWS_SECRET_ACCESS_KEY:
    required: true
  AWS_APPLICATION_ACCOUNT_ID:
    required: true
  CLOUDFORMATION_ROLE_ARN:
    required: true
  TEMPLATE_BUCKET:
    required: true
  STACK_NAME:
    required: true
  BUCKET_NAME:
    required: true

runs:
  using: composite
  steps:
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Package and deploy
      shell: bash
      run: |
        aws cloudformation package \
          --template-file apps/bucket/cloudformation.yml \
          --s3-bucket ${{ inputs.TEMPLATE_BUCKET }} \
          --output-template-file packaged.yml
        aws cloudformation deploy \
          --stack-name ${{ inputs.STACK_NAME }} \
          --template-file packaged.yml \
          --role-arn ${{ inputs.CLOUDFORMATION_ROLE_ARN }} \
          --capabilities CAPABILITY_IAM \
          --parameter-overrides \
              BucketName='${{ inputs.BUCKET_NAME }}' \
              AwsApplicationAccountId='${{ inputs.AWS_APPLICATION_ACCOUNT_ID }}'
