name: Deploy to test

on:
  push:
    branches:
      - develop

concurrency: deploy-test

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: test

    steps:

      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy-bucket
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CLOUDFORMATION_ROLE_ARN: ${{ secrets.CLOUDFORMATION_ROLE_ARN }}
          AWS_APPLICATION_ACCOUNT_ID: ${{ secrets.AWS_APPLICATION_ACCOUNT_ID }}
          TEMPLATE_BUCKET: cf-templates-1hz9ldhhl4ahu-us-west-2
          STACK_NAME: s1-orbits-bucket-test
          BUCKET_NAME: s1-orbits-test
          FETCHER_ROLE_NAME: orbits-fetcher-test

      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy-application
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CLOUDFORMATION_ROLE_ARN: ${{ secrets.CLOUDFORMATION_ROLE_ARN }}
          TEMPLATE_BUCKET: cf-templates-1hz9ldhhl4ahu-us-west-2
          STACK_NAME: s1-orbits-test
          BUCKET_NAME: s1-orbits-test
          DOMAIN_NAME: s1-orbits-test.asf.alaska.edu
          CERTIFICATE_ARN: ${{ secrets.CERTIFICATE_ARN }}
          CDSE_USERNAME: ${{ secrets.CDSE_USERNAME }}
          CDSE_PASSWORD: ${{ secrets.CDSE_PASSWORD }}
          FETCHER_ROLE_NAME: orbits-fetcher-test