name: Deploy to test

on:
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      APPLICATION_STACK_NAME:
        type: string
        description: The name to give to the application stack.
        default: s1-orbits-test
      BUCKET_STACK_NAME:
        type: string
        description: The name to give to the bucket stack.
        default: s1-orbits-bucket-test
      BUCKET_NAME:
        type: string
        description: The name to give to the bucket.
        default: s1-orbits-test 
      DOMAIN_NAME:
        type: string
        description: The domain name for the API.
        default: s1-orbits-test.asf.alaska.edu

concurrency: deploy-test

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: test

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CLOUDFORMATION_ROLE_ARN: ${{ secrets.CLOUDFORMATION_ROLE_ARN }}
          OPENDATA_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          OPENDATA_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          OPENDATA_CLOUDFORMATION_ROLE_ARN: ${{ secrets.CLOUDFORMATION_ROLE_ARN }}
          AWS_APPLICATION_ACCOUNT_ID: ${{ secrets.AWS_APPLICATION_ACCOUNT_ID }}
          CERTIFICATE_ARN: ${{ secrets.CERTIFICATE_ARN }}
          CDSE_USERNAME: ${{ secrets.CDSE_USERNAME }}
          CDSE_PASSWORD: ${{ secrets.CDSE_PASSWORD }}
          BUCKET_STACK_NAME: ${{ github.event.inputs.BUCKET_STACK_NAME || 's1-orbits-bucket-test' }}
          APP_STACK_NAME: ${{ github.event.inputs.APPLICATION_STACK_NAME || 's1-orbits-test' }}
          BUCKET_NAME: ${{ github.event.inputs.BUCKET_NAME || 's1-orbits-test' }}
          DOMAIN_NAME: ${{ github.event.inputs.DOMAIN_NAME || 's1-orbits-test.asf.alaska.edu' }}
          OPENDATA_TEMPLATE_BUCKET: cf-templates-aubvn3i9olmk-us-west-2
          TEMPLATE_BUCKET: cf-templates-aubvn3i9olmk-us-west-2