name: Deploy to AWS

on:
  push:
    branches:
      - main

env:
  STACK_NAME: asj-sentinel1-orbits
  TEMPLATE_BUCKET: cf-templates-1hz9ldhhl4ahu-us-west-2
  CLOUDFORMATION_ROLE_ARN: ${{ secrets.CLOUDFORMATION_ROLE_ARN }}
  BUCKET_NAME: asj-sentinel1-orbits
  CDSE_USERNAME: ${{ secrets.CDSE_USERNAME }}
  CDSE_PASSWORD: ${{ secrets.CDSE_PASSWORD }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-api.txt -t apps/api/src
          python -m pip install -r requirements-fetcher.txt -t apps/fetcher/src

      - name: Package and deploy
        run: |
          aws cloudformation package \
            --template-file cloudformation.yml \
            --s3-bucket ${TEMPLATE_BUCKET} \
            --output-template-file packaged.yml
          aws cloudformation deploy \
            --stack-name ${STACK_NAME} \
            --template-file packaged.yml \
            --role-arn ${CLOUDFORMATION_ROLE_ARN} \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides \
                BucketName="${BUCKET_NAME}" \
                CdseUsername="${CDSE_USERNAME}" \
                CdsePassword="${CDSE_PASSWORD}"
