name: Deploy to prod

on:
  push:
    branches:
      - main

concurrency: deploy-prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: prod

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CLOUDFORMATION_ROLE_ARN: ${{ secrets.CLOUDFORMATION_ROLE_ARN }}
          TEMPLATE_BUCKET: cf-templates-1hz9ldhhl4ahu-us-west-2
          STACK_NAME: s1-orbits
          BUCKET_NAME: s1-orbits
          DOMAIN_NAME: s1-orbits.asf.alaska.edu
          CERTIFICATE_ARN: ${{ secrets.CERTIFICATE_ARN }}
          CDSE_USERNAME: ${{ secrets.CDSE_USERNAME }}
          CDSE_PASSWORD: ${{ secrets.CDSE_PASSWORD }}
