name: Write release and finish

on:
  push:
    tags:
      - 'v*'

jobs:
  call-release-workflow:
    uses: ASFHyP3/actions/.github/workflows/reusable-release.yml@v0.11.2
    with:
      release_prefix: Sentinel-1 Orbits
    secrets:
      USER_TOKEN: ${{ secrets.GITHUB_TOKEN }}